### ISSUE TITLE
wont build

### ISSUE THREAD

**Issue by pizdjuk** [gwenhael-le-moine/x48ng#7] opened 2023-05-20 20:35 UTC
I try to build, seems that all libs are installed, but:

```
...
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:5898: referencia a `XNextEvent' sin definir
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:6458: referencia a `XRefreshKeyboardMapping' sin definir
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:5917: referencia a `XLookupString' sin definir
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:5910: referencia a `XLookupString' sin definir
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:5889: referencia a `XLookupString' sin definir
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:5967: referencia a `XFetchBuffer' sin definir
/usr/bin/ld: /home/user/tmp/x48ng/src/x48.c:6393: referencia a `XFree' sin definir
...
```

**Comment by gwenhael-le-moine** [comment] 2023-05-21 09:32
I'd say you're missing X libraries. What does `pkg-config --libs x11 xext` outputs?

**Comment by pizdjuk** [comment] 2023-05-22 05:58
> I'd say you're missing X libraries. What does `pkg-config --libs x11 xext` outputs?

-lX11 -lXext

btw., x48 (not ng) builds successfully

**Comment by gwenhael-le-moine** [comment] 2023-05-23 10:27
What is your OS?

**Comment by pizdjuk** [comment] 2023-05-28 15:36
> What is your OS?

Linux Mint (Ubuntu 20.04-based)

**Comment by gwenhael-le-moine** [comment] 2023-06-02 20:17
I just pushed a correction which allowed me to compile on Linux Mint without the debugger `make WITH_DEBUGGER=no`

It's on a just installed OS (in a VM) where I installed `libreadline-dev xorg-dev gcc`

Building including the debugger fails because pkgconfig can't find readline and/or history

**Comment by gwenhael-le-moine** [comment] 2023-06-02 20:33
Ok, I pushed a second commit that should fix this issue, including compilation `WITH_DEBUGGER=yes` (which is the default)

@pizdjuk Can you confirm it's working so I can close the issue?

**Comment by pizdjuk** [comment] 2023-06-03 22:58
> Ok, I pushed a second commit that should fix this issue, including compilation `WITH_DEBUGGER=yes` (which is the default)
> 
> @pizdjuk Can you confirm it's working so I can close the issue?

it builds now. Other thing: I try to build with WITH_DEBUGGER=no, but it builds still with -DWITH_DEBUGGER=1

**Comment by gwenhael-le-moine** [comment] 2023-06-04 06:45
> […] Other thing: I try to build with WITH_DEBUGGER=no, but it builds still with -DWITH_DEBUGGER=1

I don't reproduce that. Do you pass `WITH_DEBUGGER=no` after `make`? Like `make WITH_DEBUGGER=no`?

**Comment by pizdjuk** [comment] 2023-06-05 15:52
> > […] Other thing: I try to build with WITH_DEBUGGER=no, but it builds still with -DWITH_DEBUGGER=1
> 
> I don't reproduce that. Do you pass `WITH_DEBUGGER=no` after `make`? Like `make WITH_DEBUGGER=no`?

nope. I passed it before xD. I though that make pick it up from environment. Now it all works as expected.

**Comment by gwenhael-le-moine** [comment] 2023-06-05 16:37
> > > […] Other thing: I try to build with WITH_DEBUGGER=no, but it builds still with -DWITH_DEBUGGER=1
> > 
> > 
> > I don't reproduce that. Do you pass `WITH_DEBUGGER=no` after `make`? Like `make WITH_DEBUGGER=no`?
> 
> nope. I passed it before xD. I though that make pick it up from environment. Now it all works as expected.

Yes, that's what I expected. 

Even so, there's a way for make to pick an environment variable if it exists and so I pushed a commit that uses that. (Found @ https://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make#2826178 )

Thanks!

**Closed by gwenhael-le-moine** 2023-06-05 16:37 UTC
